/** LOCAL SQL INTEGRATION ONLY — never run against Supabase or any external DB.
 * All users, members, turns, model answers and logs below exist solely in PGlite
 * memory and are destroyed when the process closes. They are not runtime proof.
 * Run with Node >=20: npm ci && npm run test:sql
 */
import {bootstrap,fixtureDir,repoRoot} from './bootstrap.mjs';
import {readFileSync,writeFileSync} from 'node:fs';
import {randomUUID,createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const db=await bootstrap(),results=[];let migrationSha256;
const wid='e1111111-1111-4111-8111-111111111111',uid='e2222222-2222-4222-8222-222222222222',viewer='e5555555-5555-4555-8555-555555555555',outsider='e6666666-6666-4666-8666-666666666666';
const sqlPath=repoRoot+'/supabase/migrations/20260921032519_agent_ops_production_runtime.sql';
const q=async(sql,args=[])=>(await db.query(sql,args)).rows;
const rpc=async(name,args=[])=>(await q(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args))[0].result;
const role=async(r,user=uid)=>{await db.exec('reset role');await q("select set_config('request.jwt.claim.sub',$1,false)",[user]);await db.exec('set role '+r)};
const test=async(name,fn)=>{try{await fn();results.push({name,passed:true});console.log('PASS',name)}catch(e){results.push({name,passed:false,message:e.message,code:e.code,where:e.where});console.log('FAIL',name,e.message,e.code);}};
const deny=async(fn,code='42501')=>{try{await fn();throw new Error('unexpected acceptance')}catch(e){assert.equal(e.code,code)}};
const sub=async(msg='/status',request=randomUUID(),agent='review-analyst')=>{await role('authenticated');return rpc('agent_ops_submit_chat',['review-workspace',agent,null,request,msg])};
const claim=async(t,configured=true)=>{await role('service_role');return rpc('agent_ops_claim_chat',[t.id,uid,configured])};
const finish=async(t,answer='Local SQL assertion only',err=null,ms=7)=>{await role('service_role');return rpc('agent_ops_finish_chat',[t.id,uid,answer,err,'local-test',ms,null,null])};
const multi=async()=>{await role('authenticated');return rpc('agent_ops_submit_orchestration',['review-workspace','review-orchestrator',['review-analyst','review-critic'],randomUUID(),'Local SQL orchestration assertion'])};
try{
let sql=readFileSync(sqlPath,'utf8');migrationSha256=createHash('sha256').update(sql).digest('hex');if(!sql.trimEnd().endsWith('commit;'))sql+='\ncommit;';await db.exec(sql);
await db.exec(`insert into auth.users(id) values('${uid}'),('${viewer}'),('${outsider}'); insert into agent_ops.workspaces(id,slug,name) values('${wid}','review-workspace','LOCAL TEST ONLY'); insert into agent_ops.members(workspace_id,user_id,role) values('${wid}','${uid}','admin'),('${wid}','${viewer}','viewer'); insert into agent_ops.runtime_settings(workspace_id,ai_enabled,requests_per_minute,requests_per_day) values('${wid}',true,30,500); insert into agent_ops.skills(workspace_id,code,version,name,source_note) values('${wid}','chat-response','1.0.0','Local review','Local harness only');`);
const contract=JSON.parse(readFileSync(fixtureDir+'/contracts.json','utf8'))[0];contract.config.workspace='review-workspace';contract.config.requiredReturnFields=['agentId','runId','status','logging'];await q('insert into agent_ops.runtime_contracts(workspace_id,contract_key,version,contract_md,config,active) values($1,$2,$3,$4,$5,true)',[wid,contract.contract_key,contract.version,contract.contract_md,contract.config]);
await db.exec(`insert into agent_ops.agents(workspace_id,code,name,provenance,source_note,is_orchestrator) values('${wid}','review-orchestrator','Local orchestrator','user_created','Local harness only',true),('${wid}','review-analyst','Local analyst','user_created','Local harness only',false),('${wid}','review-critic','Local critic','user_created','Local harness only',false);`);
let t,c,r,request=randomUUID();
await test('authenticated submission assigns durable turn/run identity',async()=>{t=await sub('/status',request);assert.equal(t.status,'queued');await role('service_role');const row=(await q('select * from agent_ops.chat_turns where id=$1',[t.id]))[0];assert.match(row.run_id,/^[a-f0-9-]{36}$/);});
await test('identical request deduplicates to same turn',async()=>{const dup=await sub('/status',request);assert.equal(dup.id,t.id);assert.equal(dup.deduplicated,true);});
await test('conflicting duplicate request rejected',async()=>{await deny(()=>sub('different',request),'23505')});
await test('claim starts run once',async()=>{c=await claim(t);assert.equal(c.claimed,true);const dup=await claim(t);assert.equal(dup.claimed,false);assert.equal(dup.status,'running')});
await test('finish commits exact runtime row and receipt',async()=>{r=await finish(t);assert.equal(r.logging,'logged');assert.equal(r.status,'succeeded');const rows=await q('select * from agent_ops.operation_runs where run_id=$1',[r.runId]);assert.equal(rows.length,1);assert.equal(rows[0].payload.agentId,r.agentId);assert.equal(rows[0].source_turn_id,t.id);assert.equal(rows[0].source_kind,'runtime')});
await test('identical finish deduplicates without extra run row',async()=>{assert.equal((await finish(t)).runId,r.runId);assert.equal(Number((await q('select count(*) n from agent_ops.operation_runs where run_id=$1',[r.runId]))[0].n),1)});
await test('conflicting finish payload rejected',async()=>{await deny(()=>finish(t,'different'),'23505')});
await test('anonymous cannot submit or call runtime claim',async()=>{await role('anon','');await deny(()=>rpc('agent_ops_submit_chat',['review-workspace','review-analyst',null,randomUUID(),'/status']));await deny(()=>rpc('agent_ops_claim_chat',[t.id,uid,true]));});
await test('viewer cannot dispatch and authenticated cannot call service verify',async()=>{await role('authenticated',viewer);await deny(()=>rpc('agent_ops_submit_chat',['review-workspace','review-analyst',null,randomUUID(),'/status']));await deny(()=>rpc('agent_ops_verify_chat',[t.id,uid]));});
await test('outsider cannot read private turn or operation rows',async()=>{await role('authenticated',outsider);assert.equal((await q('select * from agent_ops.chat_turns')).length,0);assert.equal((await q('select * from agent_ops.operation_runs')).length,0);await deny(()=>rpc('agent_ops_chat_state',['review-workspace',null]));});
await test('revoked member cannot replay claim or verify terminal answer',async()=>{await role('postgres');await q('update agent_ops.members set active=false where user_id=$1',[uid]);await role('service_role');try{await deny(()=>rpc('agent_ops_claim_chat',[t.id,uid,true]));await deny(()=>rpc('agent_ops_verify_chat',[t.id,uid]));}finally{await role('postgres');await q('update agent_ops.members set active=true where user_id=$1',[uid]);}});
await test('missing model configuration produces durable failed run',async()=>{const task=await sub('Local model configuration failure');const result=await claim(task,false);assert.equal(result.claimed,false);assert.equal(result.errorCode,'AI_NOT_CONFIGURED');assert.equal(result.logging,'logged');assert.equal(result.status,'failed')});
await test('missing logging config key fails closed',async()=>{const task=await sub();await role('postgres');await q("update agent_ops.runtime_contracts set config=config-'sourceKind' where workspace_id=$1",[wid]);try{const result=await claim(task);assert.equal(result.errorCode,'LOGGING_CONTRACT_INVALID');assert.equal(result.logging,'logged');}finally{await role('postgres');await q('update agent_ops.runtime_contracts set config=$1 where workspace_id=$2',[contract.config,wid]);}});
let group;
await test('multi-agent parent waits for two durable child turns',async()=>{group=await multi();assert.equal(group.children.length,2);const waiting=await claim(group);assert.equal(waiting.status,'waiting_for_children');assert.equal(waiting.claimed,false);assert.equal(waiting.gate.complete,false)});
await test('multi-agent child receipts link exact root run and agent',async()=>{for(const child of group.children){await claim(child);const done=await finish(child);assert.equal(done.parentRunId,group.runId);assert.equal(done.agentId,child.agentId);assert.equal(done.logging,'logged');const row=(await q('select * from agent_ops.operation_runs where run_id=$1',[done.runId]))[0];assert.equal(row.payload.parentAgentId,'review-orchestrator');assert.equal(row.payload.trigger,'agent');assert.equal(row.parent_run_id,group.runId);}});
await test('multi-agent root only succeeds after exact child gate',async()=>{const claimed=await claim(group);assert.equal(claimed.claimed,true);assert.equal(claimed.gate.complete,true);const done=await finish(group);assert.equal(done.logging,'logged');assert.equal(done.gate.complete,true);assert.equal(done.children.length,2)});
await test('gate rejects empty, duplicate and mismatched agent/run pairs',async()=>{await role('service_role');await deny(()=>rpc('agent_ops_orchestrator_gate',['review-workspace',[],[]]),'22023');await deny(()=>rpc('agent_ops_orchestrator_gate',['review-workspace',['review-analyst','review-analyst'],group.children.map(c=>c.runId)]),'22023');const codes=group.children.map(c=>c.agentId).reverse();const gate=await rpc('agent_ops_orchestrator_gate',['review-workspace',codes,group.children.map(c=>c.runId)]);assert.equal(gate.complete,false)});
await test('failed child prevents root success and logs failed root',async()=>{const failed=await multi();for(const [i,child] of failed.children.entries()){await claim(child);await finish(child,i===0?null:'Local child',i===0?'MODEL_REJECTED':null)}const result=await claim(failed);assert.equal(result.status,'failed');assert.equal(result.errorCode,'CHILD_RUN_FAILED');assert.equal(result.logging,'logged');assert.equal(result.gate.complete,false)});
await test('running lease timeout commits failed log without re-execution',async()=>{const stale=await sub();await claim(stale);await role('postgres');await q("update agent_ops.chat_turns set started_at=clock_timestamp()-interval '4 minutes' where id=$1",[stale.id]);await role('service_role');const recovered=await rpc('agent_ops_recover_chat',[uid]);assert.equal(recovered.recovered.length,1);assert.equal(recovered.recovered[0].logging,'logged');assert.equal(recovered.recovered[0].errorCode,'WORKER_TIMEOUT')});
await test('reserved runtime runId blocks forged manual log',async()=>{const target=await sub();const claimed=await claim(target);await role('postgres');const payload={runId:claimed.runId,agentId:'review-analyst',startedAt:new Date().toISOString(),status:'success',trigger:'user',parentAgentId:null,steps:[]};await deny(()=>q("insert into agent_ops.operation_runs(workspace_id,run_id,environment,source_kind,source_id,payload,created_by) values($1,$2,'production','manual','local-review',$3,$4)",[wid,claimed.runId,payload,uid]),'23505');const result=await finish(target);assert.equal(result.logging,'logged')});
await test('expired queued request receives explicit QUEUE_TIMEOUT failed receipt',async()=>{const pending=await sub();await role('postgres');await q("update agent_ops.chat_turns set created_at=clock_timestamp()-interval '11 minutes' where id=$1",[pending.id]);await role('service_role');const recovered=await rpc('agent_ops_recover_stale_chat',['review-workspace',25]);assert.equal(recovered.count,1);assert.equal(recovered.recovered[0].errorCode,'QUEUE_TIMEOUT');assert.equal(recovered.recovered[0].status,'failed');assert.equal(recovered.recovered[0].logging,'logged');});
await test('revocation recovery logs failure but does not return private answer',async()=>{const stale=await sub();await claim(stale);await role('postgres');await q("update agent_ops.chat_turns set started_at=clock_timestamp()-interval '4 minutes' where id=$1",[stale.id]);await q('update agent_ops.members set active=false where user_id=$1',[uid]);try{await role('service_role');const result=await rpc('agent_ops_recover_stale_chat',['review-workspace',25]);assert.equal(result.count,1);assert.equal(result.recovered[0].logging,'logged');assert.equal(result.recovered[0].answer,undefined);}finally{await role('postgres');await q('update agent_ops.members set active=true where user_id=$1',[uid]);}});

}catch(e){results.push({name:'harness-or-migration',passed:false,message:e.message,code:e.code,where:e.where});console.log('ERROR',e.message,e.code,e.where)}finally{await db.close();writeFileSync(repoRoot+'/tests/security-sql-results.json',JSON.stringify({kind:'LOCAL_SQL_INTEGRATION_NOT_PRODUCTION_EVIDENCE',migrationSha256,generatedAt:new Date().toISOString(),results},null,2));console.log('RESULT',results.filter(r=>r.passed).length+'/'+results.length);if(results.some(r=>!r.passed))process.exitCode=1}
